# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  ParticalSimulation_config = debug
endif
ifeq ($(config),release)
  ParticalSimulation_config = release
endif

PROJECTS := ParticalSimulation

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

ParticalSimulation:
ifneq (,$(ParticalSimulation_config))
	@echo "==== Building ParticalSimulation ($(ParticalSimulation_config)) ===="
	@${MAKE} --no-print-directory -C . -f ParticalSimulation.make config=$(ParticalSimulation_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f ParticalSimulation.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   ParticalSimulation"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"